### PR TITLE
Re-added optional background animations - with support for current SVG spec (which was changed 2020, breaking this feature)

### PR DESCRIPTION
**Pull request by srmcgann**
At some point, the browser implementation of "foreignObject", an SVG internal component on which the background animations relied, was changed after merging this feature into master, making it necessary, now, to specify width and height for these elements. This change has been hereby addressed in this PR, which is tested and ready to merge!

live demo:
[https://cantelope.org/discord-logo_new/discord-logo_test/dist/#](https://cantelope.org/discord-logo_new/discord-logo_test/dist/#)

contact: admin@whitehotrobot.com

### CODE REVIEW

**Comment by NNTin** [comment]
Thanks for the PR. Can you also do `npm build` and commit the changes in the `build` folder?

**Comment by srmcgann** [comment]
You got it! I assume you meant the /dist/ folder... it's in there. Cheers. Let me know if you notice anything, or if you'd like anything else added.

-Scott

**Comment by NNTin** [comment]
Ah sorry. I meant the docs folder https://github.com/NNTin/discord-logo/tree/master/docs

The docs folder gets deployed: https://deploy-preview-23--practical-leavitt-e56bde.netlify.app/
image

Thank you for your awesome work :)

**Comment by srmcgann** [comment]
ah! gotcha. it's updated :)

**Comment by NNTin** [comment]
Thanks. The preview link works: https://deploy-preview-23--practical-leavitt-e56bde.netlify.app/

The code generator has a problem getting it to display the background animation
https://jsfiddle.net/qrp0mjyf/

**Comment by srmcgann** [comment]
ah! the devil is in the details they say... it's working now ;)

**Comment by NNTin** [comment]
Perfect! Thank you for the PR 🚀

**Pull request merged**
